#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Source tutorial clean functions
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

cleanCase

# Remove 0 directory
rm -rf 0 > /dev/null 2>&1

# Remove region mesh
rm -rf constant/cube/polyMesh > /dev/null 2>&1

# remove all the *.pdf files
rm -f plots/*.pdf > /dev/null 2>&1

# remove temporary files
find . -name '*~' -delete > /dev/null 2>&1

