#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# create volume fields                                                                                                                             
cp -rf origin.0 0

# generate meshes                                                                                                                                  
runApplication blockMesh
runApplication splitMeshRegions -cellZones -overwrite

# run PATOx                                                                                                                                            
runApplication PATOx

#------------------------------------------------------------------------------
