#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# remove the constantProperties file
rm -f TACOT-pyrolysis/constantProperties

# remove time folders
rm -rf [0-9]*

# remove plots
rm -f plots/*.pdf

# remove mesh
rm -rf constant/porousMat/polyMesh

# remove results folder and add an empty file for git repository
if [ -d output ]
then
    rm -rf output
    mkdir output
    touch output/empty
fi

# remove temporary files
find . -name '*~' -ls -delete
