#!/bin/sh

# Run from this directory
cd "${0%/*}" || exit 1

# Source tutorial clean functions
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

# Delete the following:
# - time directories
# - constant/polyMesh directory
# - postProcessing and VTK directories
# - log files
# - field files with a ".orig" backup
cleanCase

# Delete triSurface meshes and extendedFeatureMesh
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f  constant/triSurface/fibres.eMesh
rm -f  constant/triSurface/fibres.obj

# Delete Slurm output file
rm -f slurm-*.out > /dev/null 2>&1

# Delete beackup files
rm -f *~ > /dev/null 2>&1

#------------------------------------------------------------------------------
