#!/bin/sh

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

# aero with initialisation
scp constant/flow/thermophysicalProperties constant/thermophysicalProperties
scp constant/flow/turbulenceProperties constant/turbulenceProperties

scp system/flow/fvSchemes system/fvSchemes 
scp system/flow/fvSolution system/fvSolution 

scp -r aero.0/ 0/
scp -r system/blockMeshDict.aero system/blockMeshDict

# generate meshes
blockMesh

# run case
rhoCentralFoam

# obtain Mach Number 

rhoCentralFoam -postProcess -func MachNo

# sample

rhoCentralFoam -postProcess -func sampleDict

# -----------------------------------------------------------------------------
