#!/bin/sh

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Coupled with initialisation
scp system/fvSchemes.empty system/fvSchemes 
scp system/fvSolution.empty system/fvSolution 

scp -r coupled.0/ 0/
scp -r system/blockMeshDict.coupled system/blockMeshDict

# generate meshes
blockMesh
splitMeshRegions -cellZones -overwrite 

# run case
PATOx

# open paraview
paraFoam -touchAll
paraview

# -----------------------------------------------------------------------------
