#!/bin/sh

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

scp -r aero.0/ 0/
scp -r system/blockMeshDict.aero system/blockMeshDict

# create mesh
blockMesh 

# run case
# domain decomposition
decomposePar 

# run case on 2 processors
mpirun -np 2 rhoCentralFoam -parallel

# reconstruct domain
reconstructPar -withZero

# obtain Mach Number 

rhoCentralFoam -postProcess -func MachNo

# sample

rhoCentralFoam -postProcess -func sampleDict


# -----------------------------------------------------------------------------
