#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# remove time folders 
rm -rf [0-9]*

# remove all the *.pdf files 
rm -f plots/*.pdf

# remove meshes  
rm -rf constant/porousMat/polyMesh
rm -rf constant/polyMesh
rm -rf constant/subMat1/polyMesh

# remove output folder and add an empty file for git repository  
if [ -d output ]; then
    rm -rf output
    mkdir output
    touch output/empty
fi

# remove dynamicCode folder  
rm -rf dynamicCode

# remove the processor* folders
rm -rf processor*

# remove temporary files    
find . -name '*~' -ls -delete
