#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory                                                                                                    

# create volume fields
if [ ! -d 0 ]; then
    scp -r origin.0 0
fi

exec 3>&2 # file descriptor 3 to stderr
exec 2>&1 # stderr to stdout

# generate meshes
blockMesh
splitMeshRegions -cellZones -overwrite

exec 2>&3 # stderr to file descriptor 3

# run PATOx
PATOx
