#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -f verification/analytical_and_finiteDifference/*.txt
rm -f verification/analytical_and_finiteDifference/*.pdf

rm -rf verification/postProcessing

find . -name '*~' -ls -delete
