#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# paraview
#paraFoam -builtin  

# verification with finite difference and analytical solution
python3 verification/analytical_and_finiteDifference/1D_heat_problem.py
python3 verification/comparison.py

# -----------------------------------------------------------------------------
