#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# paraview
#paraFoam -builtin  

# verification with finite difference and analytical solution
python3 verification/analytical_and_finiteDifference/1D_heat_problem.py
python3 verification/comparison.py

# -----------------------------------------------------------------------------
