#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# remove all the *.pdf files
rm -f plots/*.pdf

find . -name '*~' -ls -delete
