#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

eval `tutoInDevel.sh` # Tutorial in development. Usage: ./Allrun <continue_flag> <error_msg>

# generate mesh
blockMesh

# run application
heatTransfer2T

# Create data
postProcess -func singleGraph

# To plot compressibleDarcy2T results, uncomment this
#./Allplot

# paraview
# paraFoam

# -----------------------------------------------------------------------------
