#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Source tutorial clean functions
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

# Delete the following:
# - time directories
# - constant/polyMesh directory
# - postProcessing and VTK directories
# - log files
# - field files with a ".orig" backup
cleanCase

# Delete triSurface meshes and extendedFeatureMesh
rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f  constant/triSurface/fibres.eMesh

# Delete Slurm output file
rm -f slurm-*.out > /dev/null 2>&1

# Delete beackup files
rm -f *~ > /dev/null 2>&1

#------------------------------------------------------------------------------
