#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# create volume fields
cp -r origin.0 0

# create polyMesh
m4 cylinderMesh.m4 > system/porousMat/blockMeshDict
blockMesh -region porousMat

# run PATOx
PATOx


# -----------------------------------------------------------------------------
