#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# remove the properties file
rm -f constant/porousMat/porousMatProperties

# remove time folders
rm -rf [0-9]*

# remove the mesh
rm -rf constant/porousMat/polyMesh

#remove output folder and add an empty file for git repository
if [ -d output ]; then
    rm -rf output
    mkdir output
    touch output/empty
fi

# remove temporary files
find . -name '*~' -ls -delete

