#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# generate mesh
blockMesh -region porousMat

# run application
PATOx

# Create data
postProcess -region  porousMat  -func singleGraph

# paraview
#paraFoam

# -----------------------------------------------------------------------------
