#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

# generate mesh
blockMesh -region porousMat

# run application
PATOx

# Create data
postProcess -region  porousMat  -func singleGraph

# paraview
#paraFoam

# -----------------------------------------------------------------------------
