#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Create 0 folder
if [ ! -d 0 ]; then
    scp -r origin.0 0
fi

# Create polyMesh
blockMesh -region porousMat

# Run PATOx
PATOx
