#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

#clean html
if [ -d html ]; then
   rm -rf html
fi

# clean DTAGS
rm -f DTAGS
