#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

cd plots
python3 plot.py
export -f defopen
find . -name \*.pdf -exec /bin/bash -c 'defopen $0' {} \;
