#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Remove files
rm -f BprimeTable*
rm -rf p_*

# Remove temporary files
find . -name '*~' -ls -delete
