#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# remove all the *.pdf files
rm -f plots/*.pdf                                                                                                                                                                                                         
# remove time folders
rm -rf [0-9]*

# remove meshes
rm -rf constant/polyMesh
rm -rf constant/tube/polyMesh

# remove output folder and add an empty file for git repository
if [ -d output ]; then
    rm -rf output
    mkdir output
    touch output/empty
fi

# remove dynamicCode folder
rm -rf dynamicCode

# remove all the *.pdf files
rm -f plots/*.PNG
rm -f plots/m.txt

# remove temporary files
find . -name '*~' -ls -delete
