#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# copy the 0 folder
if [ ! -f 0 ]; then
    cp -r origin.0 0
fi

# generate mesh blocks
 blockMesh
 splitMeshRegions -cellZones -overwrite

# run PATOx
 PATOx
#------------------------------------------------------------------------------
