#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# create volume fields
cp -rf origin.0 0

# generate meshes
blockMesh
splitMeshRegions -cellZones  -overwrite

# run case
PATOx

# -----------------------------------------------------------------------------
