#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

if [ ! -d 0 ]; then
    scp -r origin.0 0
fi
blockMesh -region porousMat
PATOx
awk '{if (NR!=1){ print $2 }}' output/porousMat/scalar/Ta_plot > results
awk '{if (NR!=1){ print $2 }}' output/porousMat/scalar/p_plot >> results
