#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions

# generate mesh with blockMesh
# blockMesh

# use mesh from gmsh
gmsh -3 verification/unstructured_gmsh/2D_square.geo verification/unstructured_gmsh/2D_square.msh
gmshToFoam verification/unstructured_gmsh/2D_square.msh
transformPoints -scale "(0.01 0.01 0.01)"
renumberMesh -overwrite

# run application
heatTransfer

# paraview
paraFoam

# -----------------------------------------------------------------------------
