#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0
rm -rf constant/porousMat/polyMesh
rm -rf constant/tank/polyMesh
rm -rf constant/polyMesh
rm -rf thermalLoad/constant/polyMesh
rm -rf thermalLoad/constant/porousMat/polyMesh
rm -rf thermalLoad/constant/tank/polyMesh
find . -name '*~' -delete
