#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf 0 > /dev/null 2>&1
rm -rf constant/porousMat/polyMesh/ > /dev/null 2>&1
rm -rf constant/tank/polyMesh/ > /dev/null 2>&1
find -name '*~' -delete > /dev/null 2>&1
