#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# create volume fields                                                                                                                             
cp -rf origin.0 0

# generate meshes                                                                                                                                  
cp -r constant/hotFlow/copy.polyMesh constant/hotFlow/polyMesh
cp -r constant/porousMat/copy.polyMesh constant/porousMat/polyMesh

# run PATOx                                                                                                         #PATOx
PATOx

#------------------------------------------------------------------------------
