#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# ---------------------  OpenFoam  --------------------------------------------

# generate mesh
blockMesh

# run application
compressibleDarcy2T

# Create output data
postProcess -func singleGraph

# ---------------------  Fenics  --------------------------------------------

# run the script
python3 Fenics/script.py

# ---------------------  Plot  --------------------------------------------

# run the script
python3 plot/script.py
