#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# remove output folder and add an empty file for git repository
if [ -d output ]; then
    rm -rf output
fi
mkdir output
touch output/empty

# remove history
rm -rf history

# remove time folders
rm -rf [0-9]*

# remove the processor folders
rm -rf processor*

# clean polyMesh
rm -rf constant/porousMat/polyMesh

# remove temporary files
find . -name '*~' -ls -delete

